steps:
  - label: ":fire: Burning test 1000 times"
    command: |
      echo "--- Preparing test database"
      bundle exec rails db:test:prepare

      echo "--- Running test 100 times in this job"
      TEST_LOCATION=$$(buildkite-agent meta-data get test_location)
      echo "Test location: $$TEST_LOCATION"

      for i in $$(seq 1 100); do
        echo "Iteration $$i/100"
        bundle exec rspec "$$TEST_LOCATION" --format progress
      done
    plugins:
      - docker-compose#v5.3.0:
          run: app
          config: docker-compose.yml
          mount-buildkite-agent: true
          env:
            - BUILDKITE_ANALYTICS_TOKEN
    secrets:
      BUILDKITE_ANALYTICS_TOKEN: KITESOCIAL_ANALYTICS_TOKEN
    env:
      RAILS_ENV: test
    parallelism: 10
