steps:
  - label: ":rspec: Run RSpec Tests"
    command: .buildkite/steps/rspec.sh
    plugins:
      - docker-compose#v5.3.0:
          run: app
          config: docker-compose.yml
          env:
            - BUILDKITE_ANALYTICS_TOKEN
    secrets:
      BUILDKITE_ANALYTICS_TOKEN: KITESOCIAL_ANALYTICS_TOKEN
    env:
      RAILS_ENV: test
